from .models import *
from pony import orm 
@orm.db_session
def sample_database(db):
    
    from passlib.hash import pbkdf2_sha256
    from datetime import date

    s1 = Student(email = "test@mail.com", password_hash = pbkdf2_sha256.hash("test"),
            name = "Test Testovich", birthdate = date(1990,10,10), access_level = 1, course_year = 2)
    s2 = Student(email = "hse@mail.com", password_hash = pbkdf2_sha256.hash("hse"),
            name = "Hse Hsevich", birthdate = date(1999,12,11), access_level = 1, course_year = 3)
    s3 = Student(email = "pepe@mail.com", password_hash = pbkdf2_sha256.hash("test"),
            name = "Pepe Frog", birthdate = date(1996,9,8), access_level = 1, course_year = 4)
    s4 = Student(email = "manutd@mail.com", access_level = 1, password_hash = pbkdf2_sha256.hash("reddevils"),
            name = "Manchester United", birthdate = date(1990,10,10), course_year = 5)

    c1 = Course(name="Web Design", description = orm.LongStr("In this track, you’ll learn how to design and build beautiful websites by learning the basic principles of design like branding, color theory, and typography which are all instrumental in the design process of a website. You’ll also learn HTML and CSS, which are the common code languages that all modern websites are built on. These are useful skills to acquire as they are needed by nearly every single business in the world to communicate to customers. By the end of this track, you’ll have all the skills required to design and build your own websites or even start a career with one of the thousands of companies that have a website."), curr_weight = 0.4, exam_weight = 0.6, credits = 3)
    c2 = Course(name="Algorithms", description = orm.LongStr("Important course if you are going to become a real professional in CS"),curr_weight = 0.5, exam_weight = 0.5, credits = 10)
    c3 = Course(name="Sample course", description = orm.LongStr("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus iaculis posuere ligula, et eleifend ex. Praesent id nisi mi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vel maximus elit. Nam sed ligula et mauris egestas egestas vitae non odio. Duis et quam vel metus efficitur facilisis. Sed rutrum congue elit non dictum. Suspendisse ut turpis a mauris ornare iaculis."), curr_weight = 0.9, exam_weight = 0.1, credits = 2)
    c4 = Course(name="Maths", description = orm.LongStr("Brush up your maths on this course"), curr_weight = 0.2, exam_weight = 0.8, credits = 1)
    c5 = Course(name="Biology", description = orm.LongStr("Revise your knowledge in biology"), curr_weight = 0.9, exam_weight = 0.1, credits = 7)

    m1 = Markings(student = s1, course = c1, curr_mark = 9, exam_mark = 8)
    m1 = Markings(student = s1, course = c2, curr_mark = 6, exam_mark = 5)
    m1 = Markings(student = s1, course = c3, curr_mark = 2, exam_mark = 7)
    m1 = Markings(student = s1, course = c4, curr_mark = 3, exam_mark = 5)
    m1 = Markings(student = s1, course = c5)

    Task(task = "Pass the course paper", owner = s1)
    Task(task = "An important task@", owner = s1)

    Event(task = "Go to the group meeting", owner = s1, date=date(2018,6,20))
    Event(task = "Elect new head of the Student Council", owner = s1, date=date(2018,6,12))

    l1 = Lesson(course_belong = c1, title = "1. Introduction", body = orm.LongStr("<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. </p><p>Curabitur sodales ligula in libero. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. Sed dignissim lacinia nunc. <b>Praesent mauris</b>. Curabitur tortor. Pellentesque nibh. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. Aenean quam. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. <b>Curabitur tortor</b>. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum.</p><p><i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condimentum velit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam nec ante. Sed lacinia, urna non tincidunt mattis, tortor neque adipiscing diam, a cursus ipsum ante quis turpis. Nulla facilisi. Ut fringilla. Suspendisse potenti. Nunc feugiat mi a tellus consequat imperdiet. Vestibulum sapien. Proin quam. Etiam ultrices. </p>"))
    l2 = Lesson(course_belong = c1, title = "2. Advandcing", body = orm.LongStr("<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. </p><p>Curabitur sodales ligula in libero. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. Sed dignissim lacinia nunc. <b>Praesent mauris</b>. Curabitur tortor. Pellentesque nibh. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. Aenean quam. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. <b>Curabitur tortor</b>. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum.</p><p><i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condimentum velit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam nec ante. Sed lacinia, urna non tincidunt mattis, tortor neque adipiscing diam, a cursus ipsum ante quis turpis. Nulla facilisi. Ut fringilla. Suspendisse potenti. Nunc feugiat mi a tellus consequat imperdiet. Vestibulum sapien. Proin quam. Etiam ultrices. </p>"))
    l3 = Lesson(course_belong = c1, title = "3. Advancing even more!", body = orm.LongStr("<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. </p><p>Curabitur sodales ligula in libero. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. Sed dignissim lacinia nunc. <b>Praesent mauris</b>. Curabitur tortor. Pellentesque nibh. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. Aenean quam. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. <b>Curabitur tortor</b>. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum.</p><p><i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condimentum velit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam nec ante. Sed lacinia, urna non tincidunt mattis, tortor neque adipiscing diam, a cursus ipsum ante quis turpis. Nulla facilisi. Ut fringilla. Suspendisse potenti. Nunc feugiat mi a tellus consequat imperdiet. Vestibulum sapien. Proin quam. Etiam ultrices. </p>"))
    l4 = Lesson(course_belong = c1, title = "4. Yeah, that's the end!", body = orm.LongStr("<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. </p><p>Curabitur sodales ligula in libero. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. Sed dignissim lacinia nunc. <b>Praesent mauris</b>. Curabitur tortor. Pellentesque nibh. <i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. Aenean quam. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. <b>Curabitur tortor</b>. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum.</p><p><i>Lorem ipsum dolor sit amet, consectetur adipiscing elit</i>. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condimentum velit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam nec ante. Sed lacinia, urna non tincidunt mattis, tortor neque adipiscing diam, a cursus ipsum ante quis turpis. Nulla facilisi. Ut fringilla. Suspendisse potenti. Nunc feugiat mi a tellus consequat imperdiet. Vestibulum sapien. Proin quam. Etiam ultrices. </p>"))

    h1 = Homework(lesson = l1, date = date(2018,6,8), description = "Complete the 1st homework")
    h2 = Homework(lesson = l2, date = date(2018,6,9), description = "Support Manchester united")
    h3 = Homework(lesson = l3, date = date(2018,6,18), description = "Deal with the mess that is your studies")

    orm.commit()

